---
- name: Install packages
  hosts: localhost
  tasks:
  - name: install vim
    package:
      name: vim
      state: present

  - name: install git
    package:
      name: git
      state: present

  - name: install tmux
    package:
      name: tmux
      state: present
